#!/usr/bin/env python

# Reference: http://wiki.xensource.com/xenwiki/XenStoreReference

from xen.xend.xenstore.xsutil import *
from xen.xend.xenstore.xswatch import *

xs = xshandle()
path = xs.get_domain_path(1) + "/mynode"

def watch_func(path, xs):
  th = xs.transaction_start()
  buf = xs.read(th, path)
  xs.transaction_end(th)
  print("Got %s" % buf)
  # Write back "somestuff" (as we change the path value, our callback function will then be called recursively because we return True!)
  th = xs.transaction_start()
  xs.write(th, path, "somestuff")
  xs.transaction_end(th)

  return True

xswatch(path, watch_func, xs)
