Document: xenstore-watch
Title: Debian xenstore-watch Manual
Author: <insert document author here>
Abstract: This manual describes what xenstore-watch is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xenstore-watch/xenstore-watch.sgml.gz

Format: postscript
Files: /usr/share/doc/xenstore-watch/xenstore-watch.ps.gz

Format: text
Files: /usr/share/doc/xenstore-watch/xenstore-watch.text.gz

Format: HTML
Index: /usr/share/doc/xenstore-watch/html/index.html
Files: /usr/share/doc/xenstore-watch/html/*.html


